vim.fn.assert_report("this is an error")
